# TJShared build
VariantDir('build', 'src');
env = Environment();

#sources = Split("build/tjtea.cpp build/tjany.cpp build/tjaction.cpp build/tjarguments.cpp build/tjcode.cpp build/tjcolor.cpp build/tjcore.cpp 
#build/tjexception.cpp build/tjfile.cpp build/tjhash.cpp");

sources = Glob("build/*.cpp");

objects = env.SharedObject(sources, CCFLAGS='-DTJ_OS_POSIX -DTJ_OS_LINUX ', LIBS=['gcc','gcc_s','pthread','stdc++']);
env.SharedLibrary('#build/tjshared', objects);
