VariantDir('build', '.');
env = Environment();
sources = Glob("build/*.cpp") + Glob("build/posix/*.cpp");

objects = env.SharedObject(sources, CCFLAGS='-DTJ_OS_POSIX -DTJ_OS_LINUX ');
env.SharedLibrary('#build/oscpack', objects);
