VariantDir('build', '.');
env = Environment();
sources = Glob("build/*.cpp");

objects = env.SharedObject(sources, CCFLAGS='-DTJ_OS_POSIX -DTJ_OS_LINUX ');
env.SharedLibrary('#build/tinyxml', objects);
